on:
  push:
    branches:
      - ${{ github.event.repository.default_branch }}
  pull_request:
    branches:
      - ${{ github.event.repository.default_branch }}

jobs:
  gradle_wrapper_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Build
        uses: gradle/gradle-build-action@v2.3.2
        with:
          arguments:
            build
