on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gradle_wrapper_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
  build_and_deploy:
    needs: gradle_wrapper_validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments:
            build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/distributions/
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.2
          
